server:
  port: 8083

spring:
  application.name: backend-gateway-client
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: articles 
          uri: http://capnews-articles-app:8050
          predicates:
            Path=/articles/**


