version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/articles:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - newscap-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - newscap-network

  news-manage-articles-app:
    build:
      context: .
      dockerfile: manage-articles/Dockerfile
    container_name: news-manage-articles-app
    ports:
      - "8090:8090"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=cap-news
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=123456
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./manage-articles/src:/src
      - ./manage-articles/pom.xml:/pom.xml
    command: mvn spring-boot:run
    networks:
      - newscap-network

  keycloak-db:
    image: postgres:13.5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak_db
    ports:
      - 5432:5432
    volumes:
      - ./data/keycloak-data:/var/lib/postgresql/data
    networks:
      - newscap-network

  kc:
    image: jboss/keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak_db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_SCHEMA: public
      KEYCLOAK_HOSTNAME: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KK_TO_RMQ_URL: rabbitmq
      KK_TO_RMQ_PORT: 5672
      KK_TO_RMQ_VHOST: "/"
      KK_TO_RMQ_EXCHANGE: amq.topic
      KK_TO_RMQ_USERNAME: admin
      KK_TO_RMQ_PASSWORD : admin
      KK_TO_RMQ_USE_TLS : false
    ports:
      - 8080:8080
    volumes:
      - ./keycloak/providers:/opt/jboss/keycloak/standalone/deployments/
    depends_on:
      - keycloak-db
      - rabbitmq
    networks:
      - newscap-network


  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - newscap-network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"



networks:
  newscap-network:
    driver: bridge

