spring:
  application.name: capnews-articles-app
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://192.168.39.23:32167/auth/realms/my_realm}
    mongodb:
      authentication-database: admin
      username: ${SPRING_DATA_MONGODB_USERNAME:root}
      password: ${SPRING_DATA_MONGODB_PASSWORD:123456}
      database: ${SPRING_DATA_MONGODB_DATABASE:capnews}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
  profiles:
    active: dev

rabbitmq:
  host: my-rabbitmq
  port: 5672
  username: admin
  password: admin

server:
  port: 8050

