apiVersion: apps/v1
kind: Deployment
metadata:
  name: amqp-deployment
  labels:
    app: amqp-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: rabbit-pod
      labels:
        app: rabbit-pod
    spec:
      containers:
        - name: rabbit-container
          image: rabbitmq:3.8-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit-secrets
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit-secrets
                  key: password 

          imagePullPolicy: Always
          ports:
            - name: management
              containerPort: 15672
            - name: query
              containerPort: 5672
      restartPolicy: Always
  selector:
    matchLabels:
      app: rabbit-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      volumes:
        - name: postgres-pv-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      containers:
        - name: keycloak-db
          image: postgres:13.5
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: keycloak_db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-pod
  template:
    metadata:
      labels:
        app: keycloak-pod
    spec:
      containers:
        - name: keycloak-container
          image: gogbog11/keycloak-rabbit:latest
          env:
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: username
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: password
            - name: DB_VENDOR
              value: "postgres"
            - name: DB_ADDR
              value: keycloak-db
            - name: DB_DATABASE
              value: keycloak_db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: db_password
            - name: DB_SCHEMA
              value: "public"
            - name: KK_TO_RMQ_URL
              value: amqp-service
            - name: KK_TO_RMQ_PORT
              value: "5672"
            - name: KK_TO_RMQ_VHOST
              value: "/"
            - name: KK_TO_RMQ_EXCHANGE
              value: "amq.topic"
            - name: KK_TO_RMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: rabbit_username
            - name: KK_TO_RMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: rabbit_password
            - name: KK_TO_RMQ_USE_TLS
              value: "false"
          ports:
            - name: http
              containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capnews-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capnews-mongodb
  template:
    metadata:
      labels:
        app: capnews-mongodb
    spec:
      volumes:
        - name: mongodb-pv-storage
          persistentVolumeClaim:
            claimName: mongodb-pv-claim

      containers:
        - name: capnews-mongodb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-pv-storage
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: capnews-secrets
                  key: username 
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: capnews-secrets
                  key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: capnews-secrets
                  key: username 
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: capnews-secrets
                  key: password
            - name: ME_CONFIG_MONGODB_SERVER
              value: capnews-mongodb-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capnews-articles-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capnews-articles-app
  template:
    metadata:
      labels:
        app: capnews-articles-app
    spec:
      volumes:
        - name: images-pv-storage
          persistentVolumeClaim:
            claimName: images-pv-claim
      containers:
        - name: capnews-articles-app
          image: gogbog11/capnews:v15
          ports:
            - containerPort: 8050
          env:

            - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
              value: "admin"
            - name: ISSUER_URI
              value: http://192.168.39.23:30028/auth/realms/my_realm
            - name: SPRING_DATA_MONGODB_HOST
              value: capnews-mongodb-service
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "cap-news"
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: capnews-secrets
                  key: username 
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: capnews-secrets
                  key: password 
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: RABBITMQ_HOST
              value: amqp-service
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "admin"
            - name: RABBITMQ_PASSWORD
              value: "admin"
          volumeMounts:
            - mountPath: /usr/app/images
              name: images-pv-storage


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kubernetes-dashboard
spec:
  rules:
  - host: dashboard.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capnews-ingress
  annotations:
    nginx.org/server-snippet: "proxy_ssl_verify off;"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000"

spec:
  rules:
  - host: capnews.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: capnews-articles-service
            port:
              number: 8050
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
spec:
  rules:
  - host: keycloak.capnews.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: keycloak-service
            port:
              number: 8080


