name: Tests

on:
  push:
    branches-ignore:
      - master

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: "adopt"

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: All the Tests and Coverage Checks
        run: cd manage-articles & mvn clean install
